mysql:
  host: localhost
  port: 3306
  username: homestead
  password: secret
  charset: utf8mb4
  dbname: mymall
  max_open_conns: 100
  max_idle_conns: 16
  conn_max_lifetime: 3600
  conn_max_idle_time: 3600
jwt:
  secret: fsdfascwegrgtecqwerty